### ISSUE TITLE
AvatarSettingsButton settings arent saved

### ISSUE THREAD

**Issue by FantasyDragon14** [Neodymium7/BetterDiscordStuff#1]
Custom Settings for actions on click of the avatar get reset to default immediately after closing the settings window.
More specifically, the action for left click stays the one you selectet, the actions for right- and middle-mouse click get reset to default.
Even changing the settings in the .config file doesnt help.

**Comment by BigFlubba** [comment]
I am getting the same issue too.

**Comment by Neodymium7** [comment]
Thanks for letting me know, I'll check it out later today and should hopefully have it fixed soon

**Comment by Neodymium7** [comment]
Should be fixed in the latest update!
