### ISSUE TITLE
[Bug] VoiceActivity All DM's gone

### ISSUE THREAD

**Issue by Eden333** [Neodymium7/BetterDiscordStuff#13]
**Addon Name and Version**
[VoiceActivity](https://github.com/Neodymium7/BetterDiscordStuff/commit/b31e60e606015c3a6322b87505dfb528014204aa)

**Describe the bug**
when enabled, all DM's disappear visually

**To Reproduce**
have VoiceActivity v1.2.0 enabled

**Expected behavior**
Direct Message list becomes empty

**Additional context**
disabling it, fixes the issue

**Comment by Aaronek10** [comment]
Same issue here.

**Comment by l29** [comment]
bump. same issue

**Comment by BlackusPL** [comment]
same issue. Lets downgrade this plugin

**Comment by BenjiThatFoxGuy** [comment]
yep, same issue.
after the update.
had to remove it.

**Comment by SmolAlli** [comment]
Please refrain from writing "same" on an issue. Just put a thumbs up. 
Also, downgrading a BD plugin will almost never make it work as it did. Plugin updates are to make it compatible with the current versions of Discord.

**Comment by Neodymium7** [comment]
Does the DM list still disappear when VoiceActivity and ZeresPluginLibrary are the only plugins enabled?

**Comment by orc4n** [comment]
I just played around a decent bit with my plugins, and I think there's a compatibility issue with [Platform Indicator](https://github.com/Strencher/BetterDiscordStuff/blob/6b3581f58ef95dcaa13079998687ab82dee24362/PlatformIndicators/APlatformIndicators.plugin.js) - either seems to work fine on their own, but once both are enabled the DM list breaks once reloaded
