### ISSUE TITLE
[Bug] - VoiceActivity

### ISSUE THREAD

**Issue by Soulivan71** [Neodymium7/BetterDiscordStuff#15]
**Addon Name and Version**
Which plugin or theme the issue applies to and which version you have installed.
VoiceActivity
v1.2.3

**Discord Version**
Which Discord version you are currently on (Stable, Canary, etc.).
Ptb 134917 (fb82b31)

**Describe the bug**
ViewButton on profile isn't working

**To Reproduce**
Just open user profile

**Screenshots**
![image](https://user-images.githubusercontent.com/36502190/177341745-78e681ca-1be7-403c-9fe9-40f481fcdfef.png)

**Comment by Soulivan71** [comment]
I have just this 
![image](https://user-images.githubusercontent.com/36502190/177342066-f9de10a7-ea29-476f-8e48-06f71dde4589.png)

**Comment by Neodymium7** [comment]
VoiceActivity does not patch into the user profile modal yet, only the popout, however it is something that I’m looking into for the future.

**Comment by Soulivan71** [comment]
Okay !
