### ISSUE TITLE
[Bug] ActivityIcon not showing gamepad icon and dropdown menu in setting

### ISSUE THREAD

**Issue by reynoldyehezkiel** [Neodymium7/BetterDiscordStuff#17]
**Addon Name and Version**
ActivityIcons

**Discord Version**
Stable 138429 (336eed7)

**Describe the bug**
not showing gamepad icon and dropdown menu in setting

**Screenshots**
![image](https://user-images.githubusercontent.com/73789263/181217877-d9433d76-6506-42c2-8722-c985bf573467.png)
The arrow is facing up, so i expect dropdown menu

**Comment by Neodymium7** [comment]
This is an issue with ZeresPluginLibrary, and I believe the developer is aware. I’ll try to find an alternative as a temporary solution.
