### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by theapathyimp** [Neodymium7/BetterDiscordStuff#18]
Addon:
ActivityIcons 1.2.6

Discord Version:
Stable 138734 (047115f)
BetterDiscord 1.5.3

Bug:
Not updating from DevilBro's plugin Repo. It says an update is required, but then downloads 1.2.5 instead of the current version.

To Reproduce:
Attempt to download update from PluginRepo

No screenshots bc I manually overwrote it.

Additional info:
This may not be anything on your end and might be something with the Repo's pull list/version info, but figured you'd want to know.

**Comment by Neodymium7** [comment]
Yeah, the update just got approved a few hours ago, so it might take some time for the website/PluginRepo to update. After a little bit it should be updating to the right version.
