### ISSUE TITLE
[Bug] Voice Activity icon doesn't change to mute if user is server-muted

### ISSUE THREAD

**Issue by jathek** [Neodymium7/BetterDiscordStuff#23]
**Addon Name and Version**
VoiceActivity 1.5.1

**Discord Version**
Stable 153481 (c00173e)

**Describe the bug**
If a user is in a voice channel but is server-muted, then the icon added by VoiceActivity is still the speaker icon instead of the mute icon.
In the below screenshot, the voice users in the member list, from top to bottom:
1. user who is server-muted
2. user who is server-muted
3. mod who is self-muted
4. mod who is unmuted
5. user who is server-muted

However, they all show the speaking/unmuted icon except for the mod who is manually muted.

**To Reproduce**
Server mute a channel and then look at the member list

**Screenshots**
![image](https://user-images.githubusercontent.com/692914/197252460-6627b09d-4fe6-4980-9c8c-1af8e1019000.png)

**Comment by Neodymium7** [comment]
Thanks for the report! I’ll take a look at it when I get back to my computer.
