### ISSUE TITLE
[Bug] VoiceActivity in Modal and DM Profile

### ISSUE THREAD

**Issue by Soulivan71** [Neodymium7/BetterDiscordStuff#25]
**Addon Name and Version**
VoiceActivity v1.5.4

**Discord Version**
Ptb 155131 (56cefd9) Host 1.0.1019 Windows 10 64-Bit (10.0.19045)

**Describe the bug**
Not display in activity like old versions ?

**Screenshots**
![image](https://user-images.githubusercontent.com/36502190/198846971-b97d9ed6-ab76-4c8e-8d0e-4ed11ccdaabc.png)
Its not popout when u clic on chat its the bigger one

**Enhancement**
Experiment profile add
![image](https://user-images.githubusercontent.com/36502190/198847058-ac80454d-24eb-45b5-aadb-081106d3b866.png)

**Comment by Neodymium7** [comment]
For the modal section, I couldn't find a way to reliably patch it in the same way I did after Discord's compiler switch a while ago. It was in the patch notes for that update that it would be temporarily removed until I can find a solution. It's not at the top of my todo list, but when I get a good chunk of free time I'll try to fix it again.

As for the suggestion, it's a great idea, and I'll look into adding a section for the plugin there in the future.

**Comment by Soulivan71** [comment]
Ok thx

**Comment by Neodymium7** [comment]
The DM profile section was just added in v1.6.0. As for the profile modal section, it’s still a pain to add it back, and I will if I ever find a good way to do it.
