### ISSUE TITLE
[Bug] Context menu (right click) when Ignore is enabled crashes Discord client

### ISSUE THREAD

**Issue by AndreDVJ** [Neodymium7/BetterDiscordStuff#28]
**Addon Name and Version**
VoiceActivity v1.5.6

**Discord Version**
Stable 163880 (4ef3df8)

**Describe the bug**
Right clicking a server to bring context menu, where you can Ignore their channels that you don't want to follow a user on, will crash the client. 

**To Reproduce**
1) Ignore enabled
2) Right-click any server

**Additional context**
Disabling the feature the client no longer crashes

**Comment by Neodymium7** [comment]
Unfortunately, I believe this is an issue with BD’s ContextMenu API. It’s already been fixed, but an update with the change hasn’t been released yet. For now, your best options are to either disable the setting temporarily or [manually install BD](https://github.com/BetterDiscord/BetterDiscord#manual-installation).

**Comment by Neodymium7** [comment]
BD just updated to v1.8.4, which includes the fix for context menu issues. After updating there shouldn’t be any more crashes.
