### ISSUE TITLE
[Bug] - AvatarSettingsButton broken

### ISSUE THREAD

**Issue by BigFlubba** [Neodymium7/BetterDiscordStuff#3]
**Addon Name and Version**
AvatarSettingsButton

**Describe the bug**
The plugin is completely broken. It hides the settings icon, but mouse actions do not work. You have to manually disable the plugin in the plugins config file for you to access the settings again.

**To Reproduce**
Enable the plugin.

**Expected behavior**
Mouse actions to work.

**Comment by Neodymium7** [comment]
I’m not experiencing this on my machine. Does it happen every time you start the plugin or does something have to happen first?

**Comment by BigFlubba** [comment]
Every time I start the plugin and/or reload Discord.

**Comment by Neodymium7** [comment]
I'm still unable to experience this myself unfortunately. I'd recommend redownloading the plugin and disabling other plugins to see if they're causing an issue if you haven't already. I'll keep looking to see if there's anything that triggers the issue on my end.

**Comment by BigFlubba** [comment]
Redownloading the plugin fixed the issue. Thanks!

**Comment by BigFlubba** [comment]
Correction. I was wrong. I'll have to further troubleshoot what is causing it.

**Comment by MxD-Sans** [comment]
Think I've accidentally found a repro for this one.
On Windows, BetterDiscord running the plugin. I rarely shutdown or reboot my PC. Locking the PC overnight with Discord running and unlocking in the morning (or just over a longer period of time during the day) had a ~80% chance (over the past week) of the plugin stop working, Discord reverting to the default behavior Click > Status. Restarting Discord (or just refreshing it via the CTRL+R hotkey) reloads everything and "fixes" it (until next time it occurs, of course).
Attached the full list of running plugins, just in case there might actually be some interference from some other stuff. Active theme ClearVision also plays around a bit with the avatar button.
All Plugins and Themes are up to date and were downloaded from the https://betterdiscord.app/ repo.
![image](https://user-images.githubusercontent.com/23498576/159152900-9a434b43-4206-4949-bfdc-6f239f04a8e4.png)

**Comment by Neodymium7** [comment]
I still haven't exactly figured out how to reproduce this myself, but here's a slightly edited version of the plugin that might be able to fix the issue for now:
[AvatarSettingsButton.txt](https://github.com/Neodymium7/BetterDiscordStuff/files/8312211/AvatarSettingsButton.txt)

You can either copy and paste the contents of the new one into the old plugin file or change to extension from .txt to .plugin.js and replace the old one. Let me know if you're still having the issues with this one.

**Comment by BigFlubba** [comment]
> Think I've accidentally found a repro for this one.
> On Windows, BetterDiscord running the plugin. I rarely shutdown or reboot my PC. Locking the PC overnight with Discord running and unlocking in the morning (or just over a longer period of time during the day) had a ~80% chance (over the past week) of the plugin stop working, Discord reverting to the default behavior Click > Status. Restarting Discord (or just refreshing it via the CTRL+R hotkey) reloads everything and "fixes" it (until next time it occurs, of course).
> Attached the full list of running plugins, just in case there might actually be some interference from some other stuff. Active theme ClearVision also plays around a bit with the avatar button.
> All Plugins and Themes are up to date and were downloaded from the https://betterdiscord.app/ repo.
> ![image](https://user-images.githubusercontent.com/23498576/159152900-9a434b43-4206-4949-bfdc-6f239f04a8e4.png)
> 

I do the same thing with my pc too. Discord is always running and I hardly ever restart, shutdown, put it to sleep, or hibernate. I always have it to auto lock when I am away and I let it idle all day when I am not using it. (For me it is more effective this way and also more efficient because we have 5Mbps DSL here with 1Mbps upload (yes that is correct it is megabits per second.) With over 2TB of games it does not help if one wants to do a 40GB patch update. (Literally takes over half a day.) RIP.) For me I found that no matter what I did (restarting discord and even going as far as reinstalling the plugin and restarting my pc) did not fix the issue. I tested it with all themes, plugins, and custom css disabled and isolated it and the issue still occured. It is weird that we are experiencing is but the author is not. I wonder if it has to deal with it on extended use and Discord doing what it knows best (breaking things). I am willing to bet that this is caused after extended use and something is breaking it. Something to consider.

Edit: Fixed spelling
