### ISSUE TITLE
[Bug] AvatarSettingsButton - Gap between name and profile picture

### ISSUE THREAD

**Issue by mutschistink** [Neodymium7/BetterDiscordStuff#34]
![Anmerkung 2023-01-14 194034](https://user-images.githubusercontent.com/118598934/212490647-40ed65ad-543b-49eb-836f-0ad9ccc3a875.png)

theres a big gap but idk why it just got like that one day

**Comment by Neodymium7** [comment]
Could you provide some more information, such as:
- Which plugin are you experiencing issues with? Based on the picture, I assume it's AvatarSettingsButton.
- What version of the plugin is it? Is it up to date?
- What version of Discord/BD are you on? Are they up to date?
- Do you have any other plugins enabled that might be causing compatibility issues?

**Comment by mutschistink** [comment]
Yes its AvatarSettingsbutton

AvatarSb is on version 2.0.3

![image](https://user-images.githubusercontent.com/118598934/212700039-b23fc477-8ece-45fc-9122-e349818856d7.png)

No tried every plugin in my folder

**Comment by Neodymium7** [comment]
Is there anything in your custom CSS that could cause issues with that area? Does the gap go back to normal when you disable the plugin?

**Comment by mutschistink** [comment]
@Neodymium7 so what did cause the Problem? :0

**Comment by Neodymium7** [comment]
It was an issue with the old style of user panel that can only be brought back with experiments, or it's possible that some people still have it instead of the new version.

**Comment by mutschistink** [comment]
ok nice and btw is it normal that the Status picker wont show up ?

(i put a long quoted text in about me)

**Comment by Neodymium7** [comment]
What do you mean exactly by the status picker won't show up. Does it not work when you right click (or whichever mouse button you have configured in the settings)?

**Comment by mutschistink** [comment]
yeah it just simply doesn't do anything just as if i selected the option "nothing"

**Comment by Neodymium7** [comment]
It still works for me. Try restarting Discord and/or reinstalling the plugin.
