### ISSUE TITLE
[Enchancement] VoiceActivity - Show all connected voice channels

### ISSUE THREAD

**Issue by rollingmoai** [Neodymium7/BetterDiscordStuff#35]
**Is your feature request related to a problem? Please describe.**
While inside a VC, You can join a VC in a different server using a different device (or simply in a new tab in Discord Web). However, VoiceActivity does not show all VCs you are joined in.

**Describe the solution you'd like**
Show all VCs you are joined in

**Describe alternatives you've considered**
None

**Additional context**

**Comment by Neodymium7** [comment]
Good idea! Unfortunately, Discord doesn't have any built-in methods for getting *all* voice states for a specific user (as far as I'm aware), and it would require some new UI and functionality to switch between the different voice states. It would be a decent amount of work for a niche feature, but I'll keep this idea in mind for the future.
