### ISSUE TITLE
AvatarSettingsButton v2.0.5 - fails to compile

### ISSUE THREAD

**Issue by ghost** [Neodymium7/BetterDiscordStuff#36]
**AvatarSettingsButton v2.0.5**

**Stable 171425 (7ddf2be)**

**An error was encountered while trying to load this plugin.**

**BetterDiscord shows a prompt of AvatarSettingsButton fails to compile.**
![1](https://user-images.githubusercontent.com/59147404/216497768-88a24d7b-332f-491e-9a9b-5fcd8cf4121d.png)
![2](https://user-images.githubusercontent.com/59147404/216497774-dbc3fc09-5f9c-4e79-b27c-8adc0012dfb3.png)

**Compilation error of AvatarSettingsButton still present even after disabling every other plugin which could have caused compatibility issues.**

**Comment by Neodymium7** [comment]
Should be fixed now, thanks for notifying me!
