### ISSUE TITLE
[Plugin Suggestion] Audit logs

### ISSUE THREAD

**Issue by RobinRMC** [Neodymium7/BetterDiscordStuff#49]
A plugin that allows you to see the audit logs of servers by logging the server locally.

**Comment by Neodymium7** [comment]
As far as I know, Discord doesn’t expose much of the data complied in audit logs to users without admin permissions, so this would be difficult, if not impossible, for that case (already ignoring the obvious privacy violations). In the case where you do have admin permissions… then just use the audit logs. Perhaps someone with more Discord knowledge would be able to implement something similar, but this isn’t something I’m interested in attempting to develop.

**Comment by RobinRMC** [comment]
I understand. Thanks for the reply.
