### ISSUE TITLE
[Bug]VoiceActivity Update and died

### ISSUE THREAD

**Issue by aunight** [Neodymium7/BetterDiscordStuff#50]
![image](https://github.com/Neodymium7/BetterDiscordStuff/assets/52199445/38a44f73-bf4f-407c-acc7-f29bf56862b1)

**Comment by Neodymium7** [comment]
Go to your plugins folder and delete the file called "VoiceActivity.config.json," then restart Discord. Let me know if the issue still persists.

**Comment by aunight** [comment]
It works thanks
