### ISSUE TITLE
[Bug] Voice activity icon not display correctly

### ISSUE THREAD

**Issue by Soulivan71** [Neodymium7/BetterDiscordStuff#51]
**Addon Name and Version**
Voice activity 1.8.4

**Discord Version**
Ptb 230873 (b902ec9) Host 1.0.1033 x86 (37675) Windows 10 64-Bit (10.0.19045)

**Describe the bug**
Icon full black or green

**Screenshots**

![image](https://github.com/Neodymium7/BetterDiscordStuff/assets/36502190/1ff4db8e-ba5b-4525-a05b-a8f1d33115fd)
![image](https://github.com/Neodymium7/BetterDiscordStuff/assets/36502190/c90ec06d-c72b-4928-b490-749e6843d285)
![image](https://github.com/Neodymium7/BetterDiscordStuff/assets/36502190/94191f55-f2c5-4402-9c64-2f9e18617434)

**Comment by pinetreemoonlight** [comment]
same issue

**Comment by Neodymium7** [comment]
I'm aware of this issue; something changed with how Discord handles and renders icons. Currently looking for a fix, but I'm also pretty busy with other things so it might be a bit.

**Comment by Soulivan71** [comment]
Thx u for reactivity <3
