### ISSUE TITLE
VoiceActivity Plugin is broken[Bug]

### ISSUE THREAD

**Issue by Zer0Three** [Neodymium7/BetterDiscordStuff#52]
**Addon Name and Version**
Which plugin or theme the issue applies to and which version you have installed.

**Discord Version**
Which Discord version you are currently on (Stable, Canary, etc.).

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Screenshots**

**Additional context**
Add any other context about the problem here. For example, any other plugins you have enabled that could cause compatibility issues.

**Comment by Neodymium7** [comment]
Duplicate of #53
