### ISSUE TITLE
VoiceActivity Plugin[Bug]

### ISSUE THREAD

**Issue by Zer0Three** [Neodymium7/BetterDiscordStuff#53]
VoiceActivity Plugin is broken

Not working on both BD in Stable and PTB

Was working fine yesterday and ever since. Opened discord today and it isnt working. A friend experiencing the same issue. I tried removing both the .js and .json files for the VoiceActivity Plugin and got it new from here and from the BD website. Reinstalled BD and still not working.

**Comment by Neodymium7** [comment]
Just came across this issue as well. Working on a fix now.
