### ISSUE TITLE
[Bug] No icons in the DM's tab

### ISSUE THREAD

**Issue by Vampical** [Neodymium7/BetterDiscordStuff#54]
**Addon Name and Version**
Which plugin or theme the issue applies to and which version you have installed.
Theme: Fluent Discord
Addon version: 1.8.6

**Discord Version**
Stable

**Describe the bug**
Not show icons in DM tab

**To Reproduce**
Return icon in DM tab

**Screenshots**
Screenshot added
![image](https://github.com/Neodymium7/BetterDiscordStuff/assets/81621343/900d94fd-37ef-4ff9-a13d-dd69842c9870)

**Comment by Neodymium7** [comment]
Thanks for notifying me! I believe I know why this is happening. Should work out a fix soon.

**Comment by Vampical** [comment]
Hi, this bug returned absolutely identical to the previous one, all the parameters are the same, only the plugin version is 1.8.8

**Comment by Vampical** [comment]
@Neodymium7 (mention it so that you can see it 100%)

**Comment by Neodymium7** [comment]
I pushed a fix for this yesterday. If it’s still not working on version 1.8.9 then let me know.
