### ISSUE TITLE
[Enchancement] VoiceActivity

### ISSUE THREAD

**Issue by Soulivan71** [Neodymium7/BetterDiscordStuff#58]
**Is your feature request related to a problem? Please describe.**
No, Is it possible to use ur plugin on vencord ? and if yes, how I can use it ?

**Comment by Neodymium7** [comment]
No, as far as I'm aware, it is not possible to use a BD plugin like VoiceActivity on Vencord. Porting my plugins to other client mods is something that's been requested before and that I do have on my radar for the future, but it would require a significant amount of a work, which I currently don't really have time for. I'll close this issue for now, but I'll keep you updated if I or anyone else does decide to port VoiceActivity to Vencord.
