### ISSUE TITLE
VoiceActivity crashes Discord on music bot hover[Bug]

### ISSUE THREAD

**Issue by zerox003** [Neodymium7/BetterDiscordStuff#6]
VoiceActivity 1.0

Crashes discord when trying to read a VC-Bots channel when they are in multiple channel at once.

**To Reproduce**
Hover over the voice icon in the meber list or just try opening the profile from a vc bot which is currently in multiple channels crashes Discord.

**Screenshots**
![image](https://user-images.githubusercontent.com/40106969/163008469-3a1ec54a-d1c5-4594-b05b-081424bd3cee.png)
![image](https://user-images.githubusercontent.com/40106969/163008569-b68a1142-1fe9-4339-98e1-a20cb5a4d8e2.png)

**Comment by Neodymium7** [comment]
Thanks for letting me know! I’ve been unable to reproduce this myself yet, but I’ll take a closer look as soon as I get the chance.

**Comment by Neodymium7** [comment]
Could you see if the new version I just pushed out fixes any of the crashes and if it causes any other unexpected issues?

**Comment by zerox003** [comment]
> Could you see if the new version I just pushed out fixes any of the crashes and if it causes any other unexpected issues?

Yes it did!
Thanks alot :D
