### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by ghost** [Neodymium7/BetterDiscordStuff#64]
**Addon Name and Version**
VoiceActivity v1.8.16

**Discord Version**
stable 292725 (485a03a) Host 1.0.9146 x64 (47543) Windows 11 64-bit (10.0.26120)

**Describe the bug**
Keeps telling me their is an update for VoiceActivity

**To Reproduce**
Launch Discord

**Screenshots**
![Screenshot 2024-05-13 220104](https://github.com/Neodymium7/BetterDiscordStuff/assets/12119604/824bcfea-1db7-40bb-8117-aff73cf5f861)

**Additional context**
I have went to the plugins download page, manually downloaded it again and reinstalled it and no fix.

**Comment by Neodymium7** [comment]
Try manually reinstalling the newest version from GitHub if you haven’t already.
