### ISSUE TITLE
[Bug] Missing icons in server list

### ISSUE THREAD

**Issue by RobinRMC** [Neodymium7/BetterDiscordStuff#69]
**Addon Name and Version**
VoiceActivity

**Discord Version**
Stable

**Describe the bug**
I'm not seeing the voice icons in the server list anymore. I can usually see a speaker icon on a server which indicates that there is someone in a voice channel in that server. I'm missing this icon since the latest update.

**Comment by Neodymium7** [comment]
The server icons are still working as intended on my end. Which version of the plugin are you on?

**Comment by RobinRMC** [comment]
v1.8.28

**Comment by RobinRMC** [comment]
I think my Discord client needed to update. Let me check if that fixed it.

**Comment by RobinRMC** [comment]
That fixed the issue indeed. I've never had it happen before that a plugin didn't work because it was more up-to-date than my Discord client.

**Comment by RobinRMC** [comment]
Oh and thanks for the fast response btw.
