### ISSUE TITLE
[Enchancement] Add notification

### ISSUE THREAD

**Issue by SaeidNH** [Neodymium7/BetterDiscordStuff#7]
If you could please make something like [this](https://github.com/danny8376/DannyAAMBetterDiscordAddons/blob/master/Plugins/VoiceChannelUserJoinNotification/VoiceChannelUserJoinNotification.plugin.js)

It's not working after Discord Feb update.
But I removed some lines and it's working, but it doesn't show the plugin in user context menu. Everything else is working.
Really appreciated it if you fix this.

**Comment by Neodymium7** [comment]
I’m currently very busy and not taking requests for plugins, but if I get a chance I’ll take a look. I can’t promise that I’ll be able to fix anything, unfortunately (I’m still fairly new to plugin development), but I’ll see what I can do.

**Comment by Neodymium7** [comment]
Sorry, Discord changed context menus to be difficult to patch, and I'm not sure how to do it now. Perhaps I'll take a look again later if I ever figure out how to get context menu patches to work.
