### ISSUE TITLE
ActivityIcons won't download ZeresPluginLibrary

### ISSUE THREAD

**Issue by Eight-P** [Neodymium7/BetterDiscordStuff#72]
`https://rauenzi.github.io/BDPluginLibrary/release/0PluginLibrary.plugin.js` returns 404

I believe Zere changed his GitHub name from rauenzi to zerebos.

https://github.com/zerebos/BDPluginLibrary

https://github.com/Neodymium7/BetterDiscordStuff/blob/f504466432dda2552943d722c7e7641885e90739/ActivityIcons/ActivityIcons.plugin.js#L63

**Comment by Neodymium7** [comment]
Yep, thanks for letting me know! I'm going to be moving away from Zere's lib fairly soon (as are most plugin devs hopefully), so I don't think it's really worth the effort to fix the link on all of my plugins just to remove it altogether.
