### ISSUE TITLE
[Bug] VoiceActivity breaks friends list

### ISSUE THREAD

**Issue by Technetium1** [Neodymium7/BetterDiscordStuff#75]
**Addon Name and Version**
Which plugin or theme the issue applies to and which version you have installed.
`VoiceActivity v1.9.1`

**Discord Version**
Which Discord version you are currently on (Stable, Canary, etc.).

`stable 353815 (a932d4a) Host 0.0.77 x64 Build Override: N/A Linux 64-bit (6.12.4-1-cachyos)`

`BetterDiscord stable 1.11.0`

**Describe the bug**
Enabling breaks the styles for friends list, showing only a couple users, and more when zoomed out.

**To Reproduce**
Steps to reproduce the behavior.

**Screenshots**
![image](https://github.com/user-attachments/assets/dff7a888-02cc-49f3-bb1a-a80e8394961b)

**Additional context**
Happens with only this plugin enabled.

**Comment by Neodymium7** [comment]
I'm not able to reproduce this. Are you getting any errors logged in the console?

**Comment by GH0STP4WZ** [comment]
I was succesfully able to reproduce this issue.
The plugin does not produce errors in the logs.
The the video here for visual proof of it happening: https://streamable.com/sawd8u

Extra information:

```md
## Discord Info
Version: canary 353880 (c748e26)
Host: 1.0.895 x64 (56390)
Build Override: N/A

## System Info
OS Version: Windows 11 64-bit (10.0.26100)

## BetterDiscord
stable 1.11.0

### Plugins (27 Enabled):
- ActivityIcons (Enabled)
- AllCallTimeCounter (Enabled)
- Animations (Enabled)
- APlatformIndicators (Enabled)
- BackgroundManager (Enabled)
- BDFDB (Enabled)
- BDToolbox
- BetterChatNames (Enabled)
- BetterDiscordExperiments (Enabled)
- BetterFolders
- BetterFormattingRedux
- ChannelsPreview
- CharCounter
- ClickToChat
- CollapsibleUI
- ColorIndicator
- ColorSighted
- CompleteTimestamps
- Discord Font
- DiscordColorways
- DiscordFreeEmojis
- DisplayNotifs
- Double Click To Edit
- EditUsers (Enabled)
- Embed More Images
- FriendCodes (Enabled)
- GameTimeTracker (Enabled)
- GifCaptioner (Enabled)
- GlobalBadges (Enabled)
- InMyVoice
- InsertTimestamps (Enabled)
- InvisibleTyping (Enabled)
- MentionFilter (Enabled)
- MessagePeek (Enabled)
- MoreRoleColors
- NoMosaic
- NoReplyPing (Enabled)
- NoSpotifyPause
- NotificationSounds (Enabled)
- OpenInApp
- PingNotification (Enabled)
- PluginRepo
- Recovery
- RedditMentions
- RemoveChatButtons
- ReplaceTimestamps
- Right Click Join
- RoleMembers
- SendStickersAsLinks
- SidebarFixer
- SocialMediaLinkConverter
- SoundpackControl
- SpotifyEnhance (Enabled)
- SpotifyListenAlong
- StickerEmojiPreview
- SuppressReplyMentions
- ThemeAttributes (Enabled)
- Timezones
- Toggle-Your-Stuff
- UrbanDictionary (Enabled)
- UserAffinities (Enabled)
- UserVoiceShow (Enabled)
- VoiceActivity (Enabled)
- VoiceEvents (Enabled)
- ZeresPluginLibrary
```

**Comment by Neodymium7** [comment]
Thanks for the video! It seems like the only DMs that aren't disappearing are the group DMs (correct me if I'm wrong). I also downloaded all of the same plugins to see if it was a compatibility issue (it's not 😭). I'll keep looking to see if I can replicate it.

**Comment by Neodymium7** [comment]
@Riddim-GLiTCH if you're able to, can you try to reproduce it again with an empty plugins folder except for VoiceActivity just to verify? Can you also let me know if you have any experiments enabled? Thanks!

**Comment by GH0STP4WZ** [comment]
> @Riddim-GLiTCH if you're able to, can you try to reproduce it again with an empty plugins folder except for VoiceActivity just to verify? Can you also let me know if you have any experiments enabled? Thanks!

I will have to do this first thing in the morning as I just logged off for today. My apologies.

**Comment by Neodymium7** [comment]
Someone on Discord helped me figure out it was a compatibility issue with PlatformIndicators (thanks! :D). I'm going to push the fix I have now, but if anyone still has the same issue after updating, please let me know.
