### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by josephisticated** [Neodymium7/BetterDiscordStuff#8]
**Addon Name and Version**
VoiceActivityv1.0

**Describe the bug**
Discord crashes when I hover over a bot's speaker icon or click on its profile that is in multiple voice channels

**To Reproduce**
Having a music bot live on more than 1 server

**Expected behavior**
Crash

**Screenshots**
![image](https://user-images.githubusercontent.com/53388005/163457978-59a8f629-ab01-493e-8bb9-ba383a176657.png)
![image](https://user-images.githubusercontent.com/53388005/163458011-0d762b2f-327c-4c39-86b4-9813fe23da09.png)

**Additional context**

**Comment by Neodymium7** [comment]
This should be fixed in the latest version. It’s not on the website yet, but you can download it from GitHub. Let me know if you still experience issues after updating.

**Comment by Neodymium7** [comment]
I’m closing this for now, but again, do let me know if you experience issues after the latest update. Thanks!
